### ISSUE TITLE
Get unclosed json result

### ISSUE THREAD

**Issue by tonyho** [scanoss/scanner.c#26]
How to reproduce:
Just clone and build the code, run the following:
```
$./scanner dist/debian/usr/include/scanoss/cyclonedx.h 
Calculating fingerprints: 0
0 Fingerprints collected in 0 ms
Scanning, please be patient...

Scan completed in: 0 ms
{
"dist/debian/usr/include/scanoss/cyclonedx.h":[{
"id":"none"
}
},
```

The result is incomplete json, missing ']' .

**Comment by mscasso-scanoss** [comment]
@tonyho Thank you for report it. I'm going to solve it ASAP and I let you know

**Comment by mscasso-scanoss** [comment]
Hi @tonyho could you give a new try? We have deprecated this code, for future scanning please refer to scanoss.py (https://github.com/scanoss/scanoss.py)
